[package]
name = "countdown"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = [
  "derive",
  "std",
], default-features = false }
rustc-hash = { version = "2.1.1", default-features = false }

[profile.release]
debug = false
lto = true
strip = true
panic = "abort"
